In [1]:
from zipfile import ZipFile
import numpy as np

In [312]:
import pandas as pd
import zipfile
import re

zf = zipfile.ZipFile('gun-violence-data_01-2013_03-2018.csv.zip') 
df = pd.read_csv(zf.open('gun-violence-data_01-2013_03-2018.csv'))

In [203]:
df.head(3)

,incident_id,date,state,city_or_county,address,n_killed,n_injured,incident_url,source_url,incident_url_fields_missing,...,participant_age,participant_age_group,participant_gender,participant_name,participant_relationship,participant_status,participant_type,sources,state_house_district,state_senate_district
0,461105,2013-01-01,Pennsylvania,Mckeesport,1506 Versailles Avenue and Coursin Street,0,4,http://www.gunviolencearchive.org/incident/461105,http://www.post-gazette.com/local/south/2013/0...,False,...,0::20,0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...,0::Male||1::Male||3::Male||4::Female,0::Julian Sims,NaN,0::Arrested||1::Injured||2::Injured||3::Injure...,0::Victim||1::Victim||2::Victim||3::Victim||4:...,http://pittsburgh.cbslocal.com/2013/01/01/4-pe...,NaN,NaN
1,460726,2013-01-01,California,Hawthorne,13500 block of Cerise Avenue,1,3,http://www.gunviolencearchive.org/incident/460726,http://www.dailybulletin.com/article/zz/201301...,False,...,0::20,0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...,0::Male,0::Bernard Gillis,NaN,0::Killed||1::Injured||2::Injured||3::Injured,0::Victim||1::Victim||2::Victim||3::Victim||4:...,http://losangeles.cbslocal.com/2013/01/01/man-...,62.0,35.0
2,478855,2013-01-01,Ohio,Lorain,1776 East 28th Street,1,3,http://www.gunviolencearchive.org/incident/478855,http://chronicle.northcoastnow.com/2013/02/14/...,False,...,0::25||1::31||2::33||3::34||4::33,0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...,0::Male||1::Male||2::Male||3::Male||4::Male,0::Damien Bell||1::Desmen Noble||2::Herman Sea...,NaN,"0::Injured, Unharmed, Arrested||1::Unharmed, A...",0::Subject-Suspect||1::Subject-Suspect||2::Vic...,http://www.morningjournal.com/general-news/201...,56.0,13.0

In [4]:
print(df.shape)

for col in df.columns: 
    print(col)

(239677, 29)
incident_id
date
state
city_or_county
address
n_killed
n_injured
incident_url
source_url
incident_url_fields_missing
congressional_district
gun_stolen
gun_type
incident_characteristics
latitude
location_description
longitude
n_guns_involved
notes
participant_age
participant_age_group
participant_gender
participant_name
participant_relationship
participant_status
participant_type
sources
state_house_district
state_senate_district

In [63]:
id_incident = []

for i in range(len(df)):
    id_ = df['incident_id'][i]
    id_2 = np.array(id_)
    incident = df['incident_characteristics'][i]
    if pd.isnull(incident) == True: 
        continue
    else:
        incident2 = np.array([re.split(r'\|\|?',p) for p in re.split(r'\|\|?', incident)]).T
        test = np.c_[id_2, incident2]
        df_test = pd.DataFrame(test)
        id_incident.append(df_test)

               
incidents = pd.concat(id_incident).reset_index().drop('index', 1)

In [66]:
incidents.head(1)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,461105,Shot - Wounded/Injured,Mass Shooting (4+ victims injured or killed ex...,Possession (gun(s) found during commission of ...,Possession of gun by felon or prohibited person,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [97]:
#incidents.columns = ['A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T']

In [ ]:
incidents['MISSING']= incidents.apply(lambda x: x.isnull().sum(), axis='columns')

In [67]:
incidents.head(2)
incidents.loc[incidents['MISSING'] == 0]

In [185]:
stacked = incidents[['B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T']].stack()
unikke = stacked.unique()

'ShotWoundedInjured'

In [313]:
unikke2 = ['Shot - Wounded/Injured',
       'Mass Shooting',
       'Possession',
       'Possession of gun by felon or prohibited person',
       'Shot - Dead', 'Gang involvement',
       'Shots Fired - No Injuries',
       'Bar/club incident - in or around establishment',
       'Officer Involved Incident',
       'Officer Involved Shooting - subject/suspect/perpetrator killed',
       'Drug involvement', 'Kidnapping/abductions/hostage',
       'Under the influence of alcohol or drugs',
       'Suicide', 'Murder/Suicide',
       'Attempted Murder/Suicide',
       'Domestic Violence', 'Home Invasion',
       'Home Invasion - Resident killed',
       'Armed robbery with injury/death and/or evidence of DGU found',
       'Drive-by',
       'Officer Involved Shooting - Officer shot',
       'Officer Involved Shooting - Officer killed',
       'Officer Involved Shooting - subject/suspect/perpetrator shot',
       'Officer Involved Shooting - subject/suspect/perpetrator suicide at standoff',
       'Spree Shooting',
       'Institution/Group/Business', 'Animal shot/killed',
       'Home Invasion - Resident injured',
       'Mass Murder',
       'Concealed Carry License - Perpetrator',
       'Stolen/Illegally owned',
       'School Incident', 'School Shooting - university/college',
       'Car-jacking', 'Hate crime', 'House party', 'Defensive Use',
       'Defensive Use - Crime occurs, victim shoots subject/suspect/perpetrator',
       'Defensive Use - Victim stops crime',
       'Workplace shooting',
       'Assault weapon',
       'Pistol-whipping', 'Implied Weapon', 'Accidental Shooting',
       'Accidental Shooting - Injury', 'Cleaning gun',
       'Brandishing/flourishing/open carry/lost/found',
       'Non-Shooting Incident', 'ATF/LE Confiscation/Raid/Arrest',
       'Unlawful purchase/sale', 'Accidental Shooting - Death',
       'BB/Pellet/Replica gun', 'Hunting accident', 'Road rage',
       'Home Invasion - No death or injury',
       'Accidental/Negligent Discharge',
       'Shots fired, no action',
       'Sex crime involving firearm', 'TSA Action',
       'Thought gun was unloaded', 'stolen from owner',
       'Gun range/gun shop/gun show shooting',
       'Home Invasion - subject/suspect/perpetrator killed',
       'Home Invasion - subject/suspect/perpetrator injured',
       'Child Involved Incident', 'Child injured self',
       'Suicide - Attempt', 'Child killed by child',
       'Self-Inflicted',
       'School Shooting - elementary/secondary school',
       'Officer Involved Incident - Weapon involved but no shots fired',
       'Defensive Use - Shots fired, no injury/death',
       'Concealed Carry License - Victim',
       'Officer Involved Shooting - Shots fired, no injury',
       'Accidental Shooting at a Business',
       'Criminal act with stolen gun', 'Child killed self',
       'Child picked up & fired gun',
       'Gun at school, no death/injury - elementary/secondary school',
       'Gun at school, no death/injury - university/college',
       'Non-Aggression Incident', 'Defensive Use - WITHOUT a gun',
       'Police Targeted',
       'Defensive Use - Stand Your Ground/Castle Doctrine established',
       'Playing with gun', 'Child injured by child',
       'Officer Involved Shooting - subject/suspect/perpetrator unarmed',
       'ShotSpotter',
       'Officer Involved Shooting - subject/suspect/perpetrator surrender at standoff',
       'Defensive Use - Good Samaritan/Third Party',
       'LOCKDOWN/ALERT ONLY: No GV Incident Occurred Onsite',
       'Child killed',
       'Child with gun - no shots fired', 'Gun shop robbery or burglary',
       'Shootout',
       'Guns stolen from law enforcement',
       'Defensive use - No shots fired',
       'Officer Involved Shooting - Bystander shot',
       'Officer Involved Shooting - Bystander killed',
       'Child injured', 'Gun buy back action',
       'Terrorism Involvement',
       'Officer Involved Shooting - Accidental discharge - no injury required',
       'Mistaken ID ',
       'Officer Involved Shooting - subject/suspect/perpetrator suicide by cop',
       'Ghost gun', 'Political Violence', 'NAV']

In [314]:
for i in unikke2: 
    df[i] = df.incident_characteristics.str.contains(i)

In [315]:
df.head(1)

,incident_id,date,state,city_or_county,address,n_killed,n_injured,incident_url,source_url,incident_url_fields_missing,...,Officer Involved Shooting - Bystander killed,Child injured,Gun buy back action,Terrorism Involvement,Officer Involved Shooting - Accidental discharge - no injury required,Mistaken ID,Officer Involved Shooting - subject/suspect/perpetrator suicide by cop,Ghost gun,Political Violence,NAV
0,461105,2013-01-01,Pennsylvania,Mckeesport,1506 Versailles Avenue and Coursin Street,0,4,http://www.gunviolencearchive.org/incident/461105,http://www.post-gazette.com/local/south/2013/0...,False,...,False,False,False,False,False,False,False,False,False,False

In [316]:
# Tjekker om vi har identificeret de rigtig variable 
col = [('False',[]),('True',[])]


for i in unikke2:    
    s = df[i].value_counts()
    s1 = list(s)
    for j in range(2): 
        col[j][1].append(s1[j])

In [321]:
Dict = {title:column for (title,column) in col}
di = pd.DataFrame(Dict)
di

      False   True
0    145425  93926
1    237714   1637
2    200299  39052
3    222186  17165
4    185942  53409
5    233674   5677
6    203601  35750
7    234761   4590
8    221363  17988
9    234696   4655
10   222252  17099
11   236674   2677
12   235857   3494
13   233244   6107
14   236439   2912
15   238882    469
16   228510  10841
17   228710  10641
18   238387    964
19   219628  19723
20   225696  13655
21   238260   1091
22   239103    248
23   235654   3697
24   238375    976
25   238953    398
26   228305  11046
27   238628    723
28   236399   2952
29   239253     98
..      ...    ...
79   237320   2031
80   239075    276
81   236301   3050
82   238343   1008
83   238776    575
84   237959   1392
85   238211   1140
86   239192    159
87   239024    327
88   238649    702
89   237063   2288
90   238813    538
91   237873   1478
92   238823    528
93   239186    165
94   238754    597
95   237020   2331
96   239118    233
97   238945    406
98   239211    140
99   239320     31
100  238315   1036
101  239220    131
102  239321     30
103  239121    230
104  239271     80
105  239203    148
106  239270     81
107  239338     13
108  239349      2

[109 rows x 2 columns]

In [282]:
range(1,2)

range(1, 2)

In [290]:
s

False    237714
True       1637
Name: Mass Shooting, dtype: int64