In [1]:
from zipfile import ZipFile
import numpy as np

In [2]:
import pandas as pd
import zipfile
import re

zf = zipfile.ZipFile('gun-violence-data_01-2013_03-2018.csv.zip') 
df = pd.read_csv(zf.open('gun-violence-data_01-2013_03-2018.csv'))

In [3]:
df.head(3)

,incident_id,date,state,city_or_county,address,n_killed,n_injured,incident_url,source_url,incident_url_fields_missing,...,participant_age,participant_age_group,participant_gender,participant_name,participant_relationship,participant_status,participant_type,sources,state_house_district,state_senate_district
0,461105,2013-01-01,Pennsylvania,Mckeesport,1506 Versailles Avenue and Coursin Street,0,4,http://www.gunviolencearchive.org/incident/461105,http://www.post-gazette.com/local/south/2013/0...,False,...,0::20,0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...,0::Male||1::Male||3::Male||4::Female,0::Julian Sims,NaN,0::Arrested||1::Injured||2::Injured||3::Injure...,0::Victim||1::Victim||2::Victim||3::Victim||4:...,http://pittsburgh.cbslocal.com/2013/01/01/4-pe...,NaN,NaN
1,460726,2013-01-01,California,Hawthorne,13500 block of Cerise Avenue,1,3,http://www.gunviolencearchive.org/incident/460726,http://www.dailybulletin.com/article/zz/201301...,False,...,0::20,0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...,0::Male,0::Bernard Gillis,NaN,0::Killed||1::Injured||2::Injured||3::Injured,0::Victim||1::Victim||2::Victim||3::Victim||4:...,http://losangeles.cbslocal.com/2013/01/01/man-...,62.0,35.0
2,478855,2013-01-01,Ohio,Lorain,1776 East 28th Street,1,3,http://www.gunviolencearchive.org/incident/478855,http://chronicle.northcoastnow.com/2013/02/14/...,False,...,0::25||1::31||2::33||3::34||4::33,0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...,0::Male||1::Male||2::Male||3::Male||4::Male,0::Damien Bell||1::Desmen Noble||2::Herman Sea...,NaN,"0::Injured, Unharmed, Arrested||1::Unharmed, A...",0::Subject-Suspect||1::Subject-Suspect||2::Vic...,http://www.morningjournal.com/general-news/201...,56.0,13.0

In [4]:
print(df.shape)

for col in df.columns: 
    print(col)

(239677, 29)
incident_id
date
state
city_or_county
address
n_killed
n_injured
incident_url
source_url
incident_url_fields_missing
congressional_district
gun_stolen
gun_type
incident_characteristics
latitude
location_description
longitude
n_guns_involved
notes
participant_age
participant_age_group
participant_gender
participant_name
participant_relationship
participant_status
participant_type
sources
state_house_district
state_senate_district

In [6]:
#print(df['incident_id'][1]

In [14]:
dataframes = []
for row in df['incident_characteristics'].dropna()[0:100]:
    incident = np.array([re.split(r'::?', p) for p in re.split(r'\|\|?', row)]).T
    dataframe = pd.DataFrame(incident)
    dataframes.append(dataframe)
    
incidents = pd.concat(dataframes).reset_index().drop('index', 1)
incidents.iloc[3]

0             Shot - Dead (murder, accidental, suicide)
1                             Officer Involved Incident
2     Officer Involved Shooting - subject/suspect/pe...
3                                      Drug involvement
4                         Kidnapping/abductions/hostage
5     Under the influence of alcohol or drugs (only ...
6                                                   NaN
7                                                   NaN
8                                                   NaN
9                                                   NaN
10                                                  NaN
11                                                  NaN
12                                                  NaN
13                                                  NaN
Name: 3, dtype: object

In [63]:
id_incident = []

for i in range(len(df)):
    id_ = df['incident_id'][i]
    id_2 = np.array(id_)
    incident = df['incident_characteristics'][i]
    if pd.isnull(incident) == True: 
        continue
    else:
        incident2 = np.array([re.split(r'\|\|?',p) for p in re.split(r'\|\|?', incident)]).T
        test = np.c_[id_2, incident2]
        df_test = pd.DataFrame(test)
        id_incident.append(df_test)

               
incidents = pd.concat(id_incident).reset_index().drop('index', 1)

In [66]:
incidents.head(1)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,461105,Shot - Wounded/Injured,Mass Shooting (4+ victims injured or killed ex...,Possession (gun(s) found during commission of ...,Possession of gun by felon or prohibited person,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [65]:
len(incidents)-len(df)

-326

In [67]:
incidents.columns = ['A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T']

In [70]:
incidents['MISSING']= incidents.apply(lambda x: x.isnull().sum(), axis='columns')

In [74]:
incidents.head(2)
incidents.loc[incidents['MISSING'] == 0]

,A,B,C,D,E,F,G,H,I,J,...,L,M,N,O,P,Q,R,S,T,MISSING
134445,599153,Shot - Wounded/Injured,"Shot - Dead (murder, accidental, suicide)",Accidental Shooting,Accidental Shooting - Death,Accidental Shooting - Injury,Accidental/Negligent Discharge,Mistaken ID (thought it was an intruder/threat...,Home Invasion,Home Invasion - Resident killed,...,Home Invasion - subject/suspect/perpetrator ki...,Defensive Use,"Defensive Use - Crime occurs, victim shoots su...",Defensive Use - Stand Your Ground/Castle Doctr...,Criminal act with stolen gun,Possession (gun(s) found during commission of ...,Gun(s) stolen from owner,Stolen/Illegally owned gun{s} recovered during...,Concealed Carry License - Victim,0

In [84]:
df.loc[df['incident_id'] == 599153]

,incident_id,date,state,city_or_county,address,n_killed,n_injured,incident_url,source_url,incident_url_fields_missing,...,participant_age,participant_age_group,participant_gender,participant_name,participant_relationship,participant_status,participant_type,sources,state_house_district,state_senate_district
134647,599153,2016-07-09,Florida,Winter Haven,5463 Laurel Oak Drive,2,1,http://www.gunviolencearchive.org/incident/599153,http://www.theledger.com/article/20160711/NEWS...,False,...,0::72||1::78||2::25,0::Adult 18+||1::Adult 18+||2::Adult 18+,0::Female||1::Male||2::Male,0::Mary McLees||1::Paul McLees||2::Ricardo Gar...,NaN,0::Injured||1::Killed||2::Killed,0::Victim||1::Victim||2::Subject-Suspect,http://www.wtsp.com/news/local/polkcounty/polk...,41.0,15.0

In [85]:
df['incident_characteristics'][134647]

'Shot - Wounded/Injured||Shot - Dead (murder, accidental, suicide)||Accidental Shooting||Accidental Shooting - Death||Accidental Shooting - Injury||Accidental/Negligent Discharge||Mistaken ID (thought it was an intruder/threat, was friend/family)||Home Invasion||Home Invasion - Resident killed||Home Invasion - Resident injured||Home Invasion - subject/suspect/perpetrator killed||Defensive Use||Defensive Use - Crime occurs, victim shoots subject/suspect/perpetrator||Defensive Use - Stand Your Ground/Castle Doctrine established||Criminal act with stolen gun||Possession (gun(s) found during commission of other crimes)||Gun(s) stolen from owner||Stolen/Illegally owned gun{s} recovered during arrest/warrant||Concealed Carry License - Victim'